package br.ufmt.alg3.telas;

import br.ufmt.alg3.dao.EmpresaDAO;
import br.ufmt.alg3.dao.FarmaceuticoDAO;
import br.ufmt.alg3.entidades.Empresa;
import br.ufmt.alg3.entidades.Farmaceutico;
import br.ufmt.alg3.factory.EmpresaFactory;
import br.ufmt.alg3.factory.FarmaceuticoFactory;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FarmaceuticoJPanel extends javax.swing.JPanel {

    private FarmaceuticoDAO dao = FarmaceuticoFactory.createDAO();
    private EmpresaDAO daoEmp = EmpresaFactory.createDAO();
    
    /**
     * Creates new form FarmaceuticoJPanel
     */
    public FarmaceuticoJPanel() {
        initComponents();
        atualizaTabela();
        atualizaTabelaEmpresa();
    }
    
    private void atualizaTabela(){
        List<Farmaceutico> tuplas = dao.listar();
        DefaultTableModel dtm = (DefaultTableModel) jTableFarmaceutico.getModel();
        int linhas = jTableFarmaceutico.getRowCount();
        for(int i = linhas - 1; i >= 0; i--){
            dtm.removeRow(i);
        }
        for(Farmaceutico farmaceutico : tuplas){
            Object[] obj = new Object[]{farmaceutico.getIdFarmaceutico(),farmaceutico.getEmpresa().getIdEmpresa(),farmaceutico.getNome(),farmaceutico.getCrf()};
            dtm.addRow(obj);
        }
    }
    
    private void atualizaTabelaEmpresa(){
        List<Empresa> tuplas = daoEmp.listar();
        DefaultTableModel dtm = (DefaultTableModel) jTableIDEmpresa.getModel();
        int linhas = jTableIDEmpresa.getRowCount();
        for(int i = linhas -1; i >= 0; i--){
            dtm.removeRow(i);
        }
        for(Empresa empresa: tuplas){
            Object[] obj = new Object[]{empresa.getIdEmpresa(), empresa.getNome()};
            dtm.addRow(obj);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTableFarmaceutico = new javax.swing.JTable();
        jLabelIDFarmaceutico = new javax.swing.JLabel();
        jTextFieldIDFarmaceutico = new javax.swing.JTextField();
        jLabelCRF = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEmpresa = new javax.swing.JLabel();
        jTextFieldIDEmpresa = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIDEmpresa = new javax.swing.JTable();
        jButtonConfirmar = new javax.swing.JButton();
        jTextFieldCRF = new javax.swing.JFormattedTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Farmacêutico"));

        jTableFarmaceutico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IDFarmaceutico", "IDEmpresa", "Nome", "CRF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTableFarmaceutico);

        jLabelIDFarmaceutico.setText("ID Farmacêutico:");

        jTextFieldIDFarmaceutico.setEditable(false);

        jLabelCRF.setText("CRF:");

        jLabelNome.setText("Nome:");

        jLabelEmpresa.setText("Empresa:");

        jTextFieldIDEmpresa.setEditable(false);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jTableIDEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Empresa", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableIDEmpresa);

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        try {
            jTextFieldCRF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIDFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIDFarmaceutico))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCRF)
                    .addComponent(jTextFieldCRF, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmpresa)
                    .addComponent(jTextFieldIDEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome))
                .addGap(0, 124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDFarmaceutico)
                    .addComponent(jLabelCRF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIDFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCRF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIDEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonEditar)
                                .addGap(41, 41, 41)
                                .addComponent(jButtonSalvar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonExcluir)
                                .addGap(41, 41, 41)
                                .addComponent(jButtonCancelar))))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // Limpar campos
        jTextFieldIDFarmaceutico.setText("");
        jTextFieldIDEmpresa.setText("");
        jTextFieldNome.setText("");
        jTextFieldCRF.setText("");
        atualizaTabela();
        atualizaTabelaEmpresa();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // Adicionar ou Alterar
        Farmaceutico farmaceutico = new Farmaceutico();
        Empresa empresa = new Empresa();
        try{
            empresa.setIdEmpresa(Integer.parseInt(jTextFieldIDEmpresa.getText()));
            farmaceutico.setEmpresa(empresa);
            farmaceutico.setNome(jTextFieldNome.getText());
            farmaceutico.setCrf(jTextFieldCRF.getText());
            try{
                int id = Integer.parseInt(jTextFieldIDFarmaceutico.getText());
                farmaceutico.setIdFarmaceutico(id);
                dao.atualizar(farmaceutico);
                JOptionPane.showMessageDialog(jTableFarmaceutico, "Atualizado com sucesso!");
            }catch(NumberFormatException e){
                dao.adicionar(farmaceutico);
                JOptionPane.showMessageDialog(jTableFarmaceutico, "Adicionado com sucesso!");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(jTableIDEmpresa, "Adicione uma empresa");
        }
        jButtonCancelarActionPerformed(evt);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // Editar
        if(jTableFarmaceutico.getSelectedRowCount() == 1){
            int linha = jTableFarmaceutico.getSelectedRow();
            jTextFieldIDFarmaceutico.setText(jTableFarmaceutico.getValueAt(linha, 0) + "");
            jTextFieldIDEmpresa.setText(jTableFarmaceutico.getValueAt(linha, 1) + "");
            jTextFieldNome.setText(jTableFarmaceutico.getValueAt(linha, 2) + "");
            jTextFieldCRF.setText(jTableFarmaceutico.getValueAt(linha, 3) + "");
            atualizaTabela();
            atualizaTabelaEmpresa();
        }else{
            if(jTableFarmaceutico.getSelectedRowCount() < 1){
                JOptionPane.showMessageDialog(jTableFarmaceutico, "Selecione ao menos 1 linha");
            }else{
                JOptionPane.showMessageDialog(jTableFarmaceutico, "Selecione 1 linha apenas");
            }
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // Excluir
        try{
            if(jTableFarmaceutico.getSelectedRowCount() >= 1){
                int[] tuplas = jTableFarmaceutico.getSelectedRows();
                for(int i = tuplas.length - 1; i >= 0; i--){
                    int id = Integer.parseInt(jTableFarmaceutico.getValueAt(tuplas[i], 0) + "");
                    dao.remover(id);
                }
                JOptionPane.showMessageDialog(jTableFarmaceutico, "Removido com sucesso");
                jButtonCancelarActionPerformed(evt);
            }else{
                JOptionPane.showMessageDialog(jTableFarmaceutico, "Selecione ao menos 1 linha");
            }
        }catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(jTableFarmaceutico, "Erro 404! Linha não existe");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // Confirmar
        if(jTableIDEmpresa.getSelectedRowCount() == 1){
            int linha = jTableIDEmpresa.getSelectedRow();
            jTextFieldIDEmpresa.setText(jTableIDEmpresa.getValueAt(linha, 0) + "");
            atualizaTabela();
            atualizaTabelaEmpresa();
        }else{
            if(jTableIDEmpresa.getSelectedRowCount() < 1){
                JOptionPane.showMessageDialog(jTableIDEmpresa, "Selecione 1 linha");
            }else if(jTableIDEmpresa.getSelectedRowCount() > 1){
                JOptionPane.showMessageDialog(jTableIDEmpresa, "Selecione 1 linha apenas");
            }
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCRF;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelIDFarmaceutico;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFarmaceutico;
    private javax.swing.JTable jTableIDEmpresa;
    private javax.swing.JFormattedTextField jTextFieldCRF;
    private javax.swing.JTextField jTextFieldIDEmpresa;
    private javax.swing.JTextField jTextFieldIDFarmaceutico;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
