package br.ufmt.alg3.telas;

import br.ufmt.alg3.dao.FabricanteDAO;
import br.ufmt.alg3.dao.ProdutoDAO;
import br.ufmt.alg3.entidades.Fabricante;
import br.ufmt.alg3.entidades.Produto;
import br.ufmt.alg3.factory.FabricanteFactory;
import br.ufmt.alg3.factory.ProdutoFactory;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ProdutoJPanel extends javax.swing.JPanel {
    
    private ProdutoDAO dao = ProdutoFactory.createDAO();
    private FabricanteDAO daoFab = FabricanteFactory.createDAO();
    
    /**
     * Creates new form ProdutoJPanel
     */
    public ProdutoJPanel() {
        initComponents();
        atualizaTabela();
        atualizaTabelaFabricante();
    }
    
    private void atualizaTabela(){
        int linhas = jTableProduto.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) jTableProduto.getModel();
        List<Produto> tuplas = dao.listar();
        for(int i = linhas - 1; i >= 0; i--){
            dtm.removeRow(i);
        }
        for(Produto produto : tuplas){
            Object[] obj = new Object[]{produto.getIdProduto(),produto.getFabricante().getIdFabricante(),produto.getNome(),produto.getPreco(),produto.getQuantidade()};
            dtm.addRow(obj);
        }
    }
    
    private void atualizaTabelaFabricante(){
        int linhas = jTableIDFabricante.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel) jTableIDFabricante.getModel();
        List<Fabricante> tuplas = daoFab.listar();
        for(int i = linhas - 1; i >= 0; i--){
            dtm.removeRow(i);
        }
        for(Fabricante fabricante : tuplas){
            Object[] obj = new Object[]{fabricante.getIdFabricante(),fabricante.getNome()};
            dtm.addRow(obj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIDFabricante = new javax.swing.JLabel();
        jLabelIDProduto = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelQuantidade = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();
        jTextFieldIDProduto = new javax.swing.JTextField();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldIDFabricante = new javax.swing.JTextField();
        jScrollPane = new javax.swing.JScrollPane();
        jTableProduto = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIDFabricante = new javax.swing.JTable();
        jButtonConfirmar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        jLabelIDFabricante.setText("ID Fabricante:");

        jLabelIDProduto.setText("ID Produto:");

        jLabelPreco.setText("Preço:");

        jLabelNome.setText("Nome:");

        jLabelQuantidade.setText("Quantidade:");

        jTextFieldIDProduto.setEditable(false);

        jTextFieldIDFabricante.setEditable(false);

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Produto", "ID Fabricante", "Nome", "Preco", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTableProduto);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableIDFabricante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Fabricante", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableIDFabricante);

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIDProduto)
                            .addComponent(jTextFieldIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPreco))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQuantidade)
                            .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelIDFabricante, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldIDFabricante, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(129, 129, 129)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jButtonConfirmar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelIDProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelPreco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIDFabricante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIDFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonExcluir)
                            .addComponent(jButtonEditar))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSalvar)
                            .addComponent(jButtonCancelar)))
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // Limpar campos
        jTextFieldIDProduto.setText("");
        jTextFieldIDFabricante.setText("");
        jTextFieldNome.setText("");
        jTextFieldPreco.setText("");
        jTextFieldQuantidade.setText("");
        atualizaTabela();
        atualizaTabelaFabricante();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // Adicionar ou alterar
        Produto produto = new Produto();
        Fabricante fabricante = new Fabricante();
        try{
            fabricante.setIdFabricante(Integer.parseInt(jTextFieldIDFabricante.getText()));
            produto.setFabricante(fabricante);
            produto.setNome(jTextFieldNome.getText());
            produto.setPreco(Double.parseDouble(jTextFieldPreco.getText()));
            produto.setQuantidade(Integer.parseInt(jTextFieldQuantidade.getText()));
            
            try{
                produto.setIdProduto(Integer.parseInt(jTextFieldIDProduto.getText()));
                dao.atualizar(produto);
                jButtonCancelarActionPerformed(evt);
                JOptionPane.showMessageDialog(jTableProduto, "Atualizado com sucesso!");
            }catch(NumberFormatException e){
                dao.adicionar(produto);
                jButtonCancelarActionPerformed(evt);
                JOptionPane.showMessageDialog(jTableProduto, "Adicionado com sucesso!");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(jTableIDFabricante,"Adicione uma empresa");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // Editar
        if(jTableProduto.getSelectedRowCount() == 1){
            int linha = jTableProduto.getSelectedRow();
            jTextFieldIDProduto.setText(jTableProduto.getValueAt(linha, 0) + "");
            jTextFieldIDFabricante.setText(jTableProduto.getValueAt(linha, 1) + "");
            jTextFieldNome.setText(jTableProduto.getValueAt(linha, 2) + "");
            jTextFieldPreco.setText(jTableProduto.getValueAt(linha, 3) + "");
            jTextFieldQuantidade.setText(jTableProduto.getValueAt(linha, 4) + "");
            atualizaTabela();
            atualizaTabelaFabricante();
        }else if(jTableProduto.getSelectedRowCount() < 1){
            JOptionPane.showMessageDialog(jTableProduto, "Selecione ao menos 1 linha");
        }else{
            JOptionPane.showMessageDialog(jTableProduto, "Selecione 1 linha apenas");
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // Excluir
        if(jTableProduto.getSelectedRowCount() >= 1){
            int[] tuplas = jTableProduto.getSelectedRows();
            for(int i = tuplas.length - 1; i >= 0; i--){
                int id = Integer.parseInt(jTableProduto.getValueAt(tuplas[i], 0) + "");
                dao.remover(id);
            }
            jButtonCancelarActionPerformed(evt);
            JOptionPane.showMessageDialog(jTableProduto, "Excluído com sucesso!");
        }else{
            JOptionPane.showMessageDialog(jTableProduto, "Selecione ao menos 1 linha");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // Confirmar
        if(jTableIDFabricante.getSelectedRowCount() == 1){
            int linha = jTableIDFabricante.getSelectedRow();
            jTextFieldIDFabricante.setText(jTableIDFabricante.getValueAt(linha, 0) + "");
            atualizaTabela();
            atualizaTabelaFabricante();
        }else if(jTableIDFabricante.getSelectedRowCount() < 1){
            JOptionPane.showMessageDialog(jTableIDFabricante, "Selecione ao menos 1 linha");
        }else{
            JOptionPane.showMessageDialog(jTableIDFabricante, "Selecione 1 linha apenas");
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelIDFabricante;
    private javax.swing.JLabel jLabelIDProduto;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelQuantidade;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableIDFabricante;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextField jTextFieldIDFabricante;
    private javax.swing.JTextField jTextFieldIDProduto;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldQuantidade;
    // End of variables declaration//GEN-END:variables
}
